name = "wow-campus-platform"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "wow-campus-platform-db"
database_id = "efaa0882-3f28-4acd-a609-4c625868d101"

[env.production]
name = "wow-campus-platform"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "wow-campus-platform-db"
database_id = "efaa0882-3f28-4acd-a609-4c625868d101"
