name = "wow-campus-platform"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[env.production]
name = "wow-campus-platform"

[env.production.vars]
ENVIRONMENT = "production"
